# Configuration STORM Optimization v2.0 - Safety Agentique
# Architecture optimisée Claude 4 Sonnet

claude:
  model: "claude-4-sonnet-20250514"
  max_tokens: 4000
  temperature: 0.1

sources:
  academic:
    - "safety_science_journal"
    - "accident_analysis_prevention"
    - "applied_ergonomics"
    - "international_journal_occupational_safety"
    - "journal_safety_research"
    - "ergonomics_international"
  
  institutional:
    - "inrs_france"
    - "niosh_usa"
    - "hse_uk"
    - "worksafebc_canada"
    - "safe_work_australia"
    - "eu_osha"
  
  sectorial:
    - "construction_safety"
    - "transport_logistics"
    - "healthcare_safety"
    - "manufacturing_operations"
    - "oil_gas_safety"
    - "mining_safety"

optimization:
  concurrent_searches: 8
  quality_threshold: 0.85
  max_sources_per_topic: 75
  performance_target: 0.55
  roi_target: 480
  
agent_targeting:
  analysis_agents: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"]
  nouveau_agents: ["AN1", "AN2", "AN3", "AN4", "AN5", "AN6", "AN7", "AN8", "AN9", "AN10"]
  reference_agents: ["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10"]
  sectorial_agents: ["SC1", "SC2", "SC3", "SC4", "SC5"]

performance_targets:
  daily_topics: 25
  weekly_agents_enhanced: 45
  monthly_performance_gain: 55
  annual_roi: 480
